%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\rjohn\OneDrive\Desktop\PhD Work\DIC_Stress_Strain\dataset run through\HCaP08\HCaP.08.xlsx
%    Worksheet: Zwick_Data
%
% Auto-generated by MATLAB on 06-Mar-2020 22:11:56

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = "Zwick_Data";
opts.DataRange = "A6:L279"; %put calculated strain in L

% Specify column names and types
opts.VariableNames = ["Standardtravel", "Standardforce", "Strain", "Stress", "Time", "Toolseparation", "Cyclenumber", "VarName8", "StressMpa", "VarName10", "StressMpa1", "CalcStrain"];
opts.SelectedVariableNames = ["Standardtravel", "Standardforce", "Strain", "Stress", "Time", "Toolseparation", "Cyclenumber", "VarName8", "StressMpa", "VarName10", "StressMpa1", "CalcStrain"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "string", "double", "string", "double", "double"];
opts = setvaropts(opts, [8, 10], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [8, 10], "EmptyFieldRule", "auto");

% Setup rules for import
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts = setvaropts(opts, [1,  2,  3,  4,  5,  6,  7,  9, 11], "TreatAsMissing", '');

% Import the data
zwickData = readtable("D:\Everything\DTI + mech test plaques\Samples\Plaque 28 - in vivo\ZwicktoDIC\28_CC1-(M)\28CC1M.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts